input:  
  default_file: input\2024-12-12_taxonomie-complete.xlsx  
  
transformation:  
  namespace: http://data4wallonia.com/  
  rules:  
    logfile: changes.log  
    changes:  
      - changelabel:  
          from: "&-()\/"  
          to: " "  
          exceptions:
          - ""
output:  
  default_file: output\output.ttl  
  default_format: text/turtle  
  
validation:  
  server: http://localhost:8080/shacl/d4wta-ap/api/validate  
  version: "v1.0.0"
