input:  
  default_file: input\2024-12-12_taxonomie-complete.xlsx 
  highest_level: "2"
  lowest_level: "5"
  information_by_level:
    Concept: "Slug Catégorie L"
    prefLabel: "Titre Catégorie L"
    Definition: "Description Catégorie L"
    ID: "ID catégorie L"  
    altLabel: ""
  
transformation:
  #namespace is the base to create URI for the concepts  
  namespace: http://data4wallonia.com/
  #default_language is the default language suffix for labels and definitions
  default_language: fr
  #default_version indicates the initial version number for the concepts, in the semantic versioning format
  default_version: "0.0.1"
  #default_status is the URI of the default status of a concept
  default_status: http://publications.europa.eu/resource/authority/concept-status/CURRENT
  #creation_date is the initial date used for the concept scheme, in the YYYY-MM-DD format
  creation_date: "2024-12-25"
  #check_mispell, if enabled, verifies typos in the concept definitions checking against French and English vocabularies and report in the log file
  check_mispell: True
  #create_english_labels, if enabled, creates english labels for the concepts if they look like containing English words 
  create_english_labels: True
  rules:  
    changes:  
      - changelabel:  
          from: "-()\/"  
          to: " "  
          exceptions:
          - ""
      - change&:
          from: "&"  
          to: "et"  
          exceptions:
          - ""
output:  
  default_file: output\output.ttl  
  default_format: text/turtle  
  
validation:  
  server: http://localhost:8080/shacl/d4wta-ap/api/validate  
  version: "v1.0.0"

logfile: changes.log
